"""Trigger Engine — evaluates events against rules and decides when to wake AI.

The Trigger Engine is the gatekeeper between the Event Bus and the Autonomous Loop.
It prevents:
- Waking AI on every minor event (cooldown, batching)
- Infinite loops from high-frequency events
- Auto-executing dangerous operations from sensor/screen changes

Architecture reference: docs/architecture.md §6.2, §6.4
"""

from __future__ import annotations

import re
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any

from ellie_schema.models import Event, EventPriority, ServerType


# ═══════════════════════════════════════════════════════════════
# Action Type — what kind of AI response to trigger
# ═══════════════════════════════════════════════════════════════

class ActionType(Enum):
    """What the Autonomous Loop should do in response to a trigger."""
    NOTIFY = auto()          # Inform user (low urgency)
    OBSERVE = auto()         # Gather more context, no action
    RESEARCH = auto()        # Deep-dive investigation
    ASSIST = auto()          # Proactive user assistance
    SELF_DEV = auto()        # Self-improvement task
    ALERT = auto()           # High-urgency alert to user


# ═══════════════════════════════════════════════════════════════
# Trigger Rule
# ═══════════════════════════════════════════════════════════════

@dataclass
class TriggerRule:
    """A rule that defines when the Trigger Engine should wake the AI.

    Rules are matched against incoming events. When a rule matches,
    a TaskRequest is generated (subject to cooldown).
    """

    # ── Identity ──
    rule_id: str = ""
    description: str = ""

    # ── Match conditions (ALL must match) ──
    event_type_pattern: str = "*"       # Glob or regex pattern for event_type
    source_type: ServerType | None = None  # None = any server type
    min_severity: int = 0               # Minimum severity (0–10)
    min_priority: EventPriority = EventPriority.BACKGROUND

    # ── Action ──
    action_type: ActionType = ActionType.NOTIFY
    action_params: dict[str, Any] = field(default_factory=dict)

    # ── Cooldown ──
    cooldown_seconds: float = 60.0      # Minimum seconds between activations
                                         # 0 = no cooldown (use with caution!)
    cooldown_key: str = ""              # Custom cooldown scope key
                                         # Empty = use rule_id as scope

    # ── State ──
    enabled: bool = True

    def get_cooldown_key(self) -> str:
        """Key used for cooldown tracking."""
        return self.cooldown_key or self.rule_id

    def matches(self, event: Event) -> bool:
        """Check if this rule matches the given event."""
        if not self.enabled:
            return False

        # Server type filter
        if self.source_type is not None and event.source_server_type != self.source_type:
            return False

        # Severity filter
        if event.severity < self.min_severity:
            return False

        # Priority filter (lower numeric value = higher priority)
        # Reject if event priority is numerically greater (lower importance)
        if event.priority.value > self.min_priority.value:
            return False

        # Event type pattern (glob-style: * matches anything, ? matches one char)
        if not self._match_pattern(self.event_type_pattern, event.event_type):
            return False

        return True

    @staticmethod
    def _match_pattern(pattern: str, value: str) -> bool:
        """Match a glob-style pattern against a value.

        Supports: * (any chars), ? (one char).
        Converts to regex for matching.
        """
        if pattern == "*":
            return True
        # Escape regex special chars, then convert glob to regex
        regex = re.escape(pattern).replace(r"\*", ".*").replace(r"\?", ".")
        regex = f"^{regex}$"
        return re.match(regex, value) is not None


# ═══════════════════════════════════════════════════════════════
# Task Request — what the Trigger Engine asks the AI to do
# ═══════════════════════════════════════════════════════════════

@dataclass
class TaskRequest:
    """A request for the Autonomous Loop to process.

    Generated by the Trigger Engine when a rule matches an event.
    This is passed to the Autonomous Loop — no LLM call happens here.
    """

    task_id: str = ""
    action_type: ActionType = ActionType.NOTIFY
    triggered_by_event_id: str = ""
    triggered_by_event_type: str = ""
    triggered_by_rule_id: str = ""
    source_server_type: ServerType = ServerType.UNSPECIFIED
    source_server_id: str = ""

    # Context snapshot at trigger time
    context_summary: str = ""
    payload_snapshot: str = "{}"

    # Priority of the task
    priority: EventPriority = EventPriority.NORMAL

    created_at_ms: int = 0
    cooldown_until_ms: int = 0


# ═══════════════════════════════════════════════════════════════
# Trigger Engine
# ═══════════════════════════════════════════════════════════════

@dataclass
class TriggerStats:
    """Runtime statistics for the Trigger Engine."""
    events_received: int = 0
    rules_matched: int = 0
    tasks_generated: int = 0
    activations_suppressed_by_cooldown: int = 0
    activations_suppressed_by_no_match: int = 0


class TriggerEngine:
    """Evaluates events against TriggerRules and generates TaskRequests.

    The Trigger Engine subscribes to the EventBus and decides:
    - Whether an event justifies waking the Autonomous Loop
    - What kind of task to generate (NOTIFY, RESEARCH, ASSIST, SELF_DEV, ALERT)
    - Whether cooldown prevents activation

    Constraints (per architecture §6.4):
    - Always wake: User request, test failure, security events
    - Wake if threshold: Multiple related events, anomalies, goal-relevant events
    - Defer: Low-priority events, routine sensor readings (batched)
    - Ignore: Known noise, duplicates (handled by EventBus)

    Usage:
        engine = TriggerEngine()
        engine.add_rule(TriggerRule(
            rule_id="test-failure",
            event_type_pattern="dev.test_*",
            min_severity=7,
            action_type=ActionType.SELF_DEV,
            cooldown_seconds=300,
        ))
        # Subscribe to EventBus
        bus.subscribe(engine.on_event)
    """

    # Default max queued tasks before oldest is dropped
    MAX_TASK_QUEUE = 100

    def __init__(self) -> None:
        self._rules: dict[str, TriggerRule] = {}
        self._cooldowns: dict[str, float] = {}       # cooldown_key → next_allowed_at (monotonic)
        self._task_queue: list[TaskRequest] = []
        self.stats = TriggerStats()

    # ── Rule Management ──────────────────────────────────────

    def add_rule(self, rule: TriggerRule) -> None:
        """Register a trigger rule."""
        if not rule.rule_id:
            rule.rule_id = f"rule_{uuid.uuid4().hex[:8]}"
        self._rules[rule.rule_id] = rule

    def remove_rule(self, rule_id: str) -> bool:
        """Remove a trigger rule. Returns True if found."""
        return self._rules.pop(rule_id, None) is not None

    def list_rules(self) -> list[TriggerRule]:
        """Return all registered rules."""
        return list(self._rules.values())

    def get_rule(self, rule_id: str) -> TriggerRule | None:
        """Get a rule by ID."""
        return self._rules.get(rule_id)

    # ── Event Handler (subscribe this to EventBus) ────────────

    def on_event(self, event: Event) -> TaskRequest | None:
        """Handle an incoming event. Called by EventBus subscriber.

        Returns a TaskRequest if a rule matched and cooldown allows,
        or None if no action should be taken.
        """
        self.stats.events_received += 1

        # Find matching rules
        matched_rules = [r for r in self._rules.values() if r.matches(event)]

        if not matched_rules:
            self.stats.activations_suppressed_by_no_match += 1
            return None

        self.stats.rules_matched += len(matched_rules)

        # Try each matching rule until one passes cooldown
        for rule in matched_rules:
            if self._check_cooldown(rule):
                # Generate task
                task = self._create_task(event, rule)
                self._task_queue.append(task)

                # Limit queue size
                if len(self._task_queue) > self.MAX_TASK_QUEUE:
                    self._task_queue.pop(0)

                self.stats.tasks_generated += 1
                return task

        # All matching rules are in cooldown
        self.stats.activations_suppressed_by_cooldown += 1
        return None

    # ── Task Queue ────────────────────────────────────────────

    def drain_tasks(self) -> list[TaskRequest]:
        """Drain and return all pending tasks (for the Autonomous Loop)."""
        tasks = list(self._task_queue)
        self._task_queue.clear()
        return tasks

    def pending_task_count(self) -> int:
        """Number of tasks waiting for the Autonomous Loop."""
        return len(self._task_queue)

    # ── Cooldown Management ──────────────────────────────────

    def _check_cooldown(self, rule: TriggerRule) -> bool:
        """Check if the rule is in cooldown. If not, start cooldown."""
        if rule.cooldown_seconds <= 0:
            return True

        key = rule.get_cooldown_key()
        now = time.monotonic()
        next_allowed = self._cooldowns.get(key, 0.0)

        if now < next_allowed:
            return False

        # Start cooldown
        self._cooldowns[key] = now + rule.cooldown_seconds
        return True

    def reset_cooldown(self, rule_id: str) -> None:
        """Reset cooldown for a specific rule (useful for testing)."""
        rule = self._rules.get(rule_id)
        if rule:
            self._cooldowns.pop(rule.get_cooldown_key(), None)

    def reset_all_cooldowns(self) -> None:
        """Reset all cooldowns."""
        self._cooldowns.clear()

    # ── Internal ─────────────────────────────────────────────

    def _create_task(self, event: Event, rule: TriggerRule) -> TaskRequest:
        """Create a TaskRequest from an event and matching rule."""
        now_ms = int(time.time() * 1000)
        cooldown_ms = int((time.monotonic() + rule.cooldown_seconds) * 1000)

        return TaskRequest(
            task_id=f"task_{uuid.uuid4().hex[:8]}",
            action_type=rule.action_type,
            triggered_by_event_id=event.event_id,
            triggered_by_event_type=event.event_type,
            triggered_by_rule_id=rule.rule_id,
            source_server_type=event.source_server_type,
            source_server_id=event.source_server_id,
            context_summary=(
                f"Event '{event.event_type}' from {event.source_server_type.name} "
                f"(severity={event.severity}, priority={event.priority.name})"
            ),
            payload_snapshot=event.payload_json,
            priority=event.priority,
            created_at_ms=now_ms,
            cooldown_until_ms=cooldown_ms,
        )


# ── Default Rules Factory ────────────────────────────────────

def create_default_rules() -> list[TriggerRule]:
    """Create a sensible set of default trigger rules.

    These rules follow the architecture's guidance (§6.4):
    - Always wake for: test failures, security events, user requests
    - Conditional wake for: anomalies, goal-relevant events
    - Defer: routine sensor readings, low-priority info
    """
    return [
        # ── Dev: Test failures — always wake ──
        TriggerRule(
            rule_id="dev-test-failure",
            description="CI test failure — investigate immediately",
            event_type_pattern="dev.test_failed",
            min_severity=7,
            min_priority=EventPriority.URGENT,
            action_type=ActionType.SELF_DEV,
            cooldown_seconds=300,  # 5 min between investigation attempts
        ),
        TriggerRule(
            rule_id="dev-ci-error",
            description="CI/CD pipeline error",
            event_type_pattern="dev.ci_error",
            min_severity=8,
            min_priority=EventPriority.URGENT,
            action_type=ActionType.SELF_DEV,
            cooldown_seconds=300,
        ),

        # ── PC: Screen changes — conditional wake ──
        TriggerRule(
            rule_id="pc-screen-change",
            description="PC screen/active window changed — check if assistance needed",
            event_type_pattern="pc.screen_changed",
            min_severity=2,
            min_priority=EventPriority.NORMAL,
            action_type=ActionType.OBSERVE,
            cooldown_seconds=30,  # Don't react to every frame
        ),

        # ── Android: Notifications — conditional wake ──
        TriggerRule(
            rule_id="android-notification",
            description="Android notification received — check if important",
            event_type_pattern="android.notification_received",
            min_severity=3,
            min_priority=EventPriority.NORMAL,
            action_type=ActionType.NOTIFY,
            cooldown_seconds=15,
        ),
        TriggerRule(
            rule_id="android-call",
            description="Incoming call — high priority",
            event_type_pattern="android.incoming_call",
            min_severity=6,
            min_priority=EventPriority.URGENT,
            action_type=ActionType.NOTIFY,
            cooldown_seconds=30,
        ),

        # ── Room: Sensor updates — defer (batch process) ──
        TriggerRule(
            rule_id="room-temperature-change",
            description="Temperature changed significantly",
            event_type_pattern="room.temperature_changed",
            min_severity=4,
            min_priority=EventPriority.BACKGROUND,
            action_type=ActionType.NOTIFY,
            cooldown_seconds=600,  # 10 min — temperature changes slowly
        ),
        TriggerRule(
            rule_id="room-motion-detected",
            description="Motion detected — check if unusual",
            event_type_pattern="room.motion_detected",
            min_severity=3,
            min_priority=EventPriority.NORMAL,
            action_type=ActionType.OBSERVE,
            cooldown_seconds=120,  # 2 min — motion is frequent
        ),

        # ── Browser/Web: Updates — conditional wake ──
        TriggerRule(
            rule_id="web-rss-updated",
            description="RSS feed updated — check for relevant content",
            event_type_pattern="web.rss_updated",
            min_severity=2,
            min_priority=EventPriority.BACKGROUND,
            action_type=ActionType.RESEARCH,
            cooldown_seconds=1800,  # 30 min — don't check RSS too often
        ),
        TriggerRule(
            rule_id="web-github-issue",
            description="New GitHub issue on AEGIS repo",
            event_type_pattern="web.github_new_issue",
            min_severity=5,
            min_priority=EventPriority.NORMAL,
            action_type=ActionType.SELF_DEV,
            cooldown_seconds=600,
        ),

        # ── Security: Always wake ──
        TriggerRule(
            rule_id="security-alert",
            description="Security-relevant event — immediate attention",
            event_type_pattern="*.security_*",
            min_severity=9,
            min_priority=EventPriority.URGENT,
            action_type=ActionType.ALERT,
            cooldown_seconds=0,  # No cooldown for security alerts
        ),

        # ── Catch-all: High-severity unknown events ──
        TriggerRule(
            rule_id="high-severity-catchall",
            description="Any event with severity >= 9 — alert user",
            event_type_pattern="*",
            min_severity=9,
            min_priority=EventPriority.URGENT,
            action_type=ActionType.ALERT,
            cooldown_seconds=60,
        ),
    ]
