package com.aegis.android.ui.designsystem

import androidx.compose.ui.graphics.Color

// Generated by scripts/generate-design-tokens.py. Do not edit by hand.
val AegisBackground = Color(0xFF05090F)
val AegisSurface = Color(0xFF0B111B)
val AegisSurfaceElevated = Color(0xFF111A27)
val AegisSurfaceMuted = Color(0xFF162133)
val AegisBorder = Color(0xFF1E2A3A)
val AegisText = Color(0xFFEAF2FF)
val AegisTextSecondary = Color(0xFF8EA0B8)
val AegisTextMuted = Color(0xFF5F718B)
val AegisCyan = Color(0xFF29D3FF)
val AegisViolet = Color(0xFF8B7CFF)
val AegisSuccess = Color(0xFF2DD4A8)
val AegisWarning = Color(0xFFFFB84D)
val AegisCritical = Color(0xFFFF5D73)
val AegisOffline = Color(0xFF7C8798)
val AegisWhite = Color(0xFFFFFFFF)
