//! Capability safety definitions for PC Server.

use serde::{Deserialize, Serialize};

/// Safety level (matches AEGIS Core's SafetyLevel enum).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u8)]
pub enum SafetyLevel {
    Level0Read = 1,
    Level1SafeAct = 2,
    Level2Approval = 3,
    Level3Restricted = 4,
}

/// Capability definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub safety_level: SafetyLevel,
    pub requires_approval: bool,
    pub side_effects: Vec<String>,
    pub timeout_ms: u32,
    pub tags: Vec<String>,
}

/// Get all registered PC Server capabilities.
pub fn get_capabilities() -> Vec<CapabilityDef> {
    vec![
        // ── Observe (Level 0: Read-only) ──────────────────
        CapabilityDef {
            id: "pc.get_screenshot".into(),
            name: "Screenshot Capture".into(),
            description: "Capture the current display as a PNG image.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 5000,
            tags: vec!["screenshot".into(), "observe".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.get_active_window".into(),
            name: "Get Active Window".into(),
            description: "Return the title, process, and position of the foreground window.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 1000,
            tags: vec!["window".into(), "observe".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.list_windows".into(),
            name: "List Windows".into(),
            description: "List all visible windows with title and process info.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 2000,
            tags: vec!["window".into(), "observe".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.get_clipboard".into(),
            name: "Get Clipboard".into(),
            description: "Read the current clipboard text (secrets are redacted).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 500,
            tags: vec!["clipboard".into(), "observe".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.get_os_info".into(),
            name: "Get OS Info".into(),
            description: "Return OS name, version, hostname, username, and architecture.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 1000,
            tags: vec!["os".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.get_screen_size".into(),
            name: "Get Screen Size".into(),
            description: "Return the screen resolution (width, height).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 500,
            tags: vec!["screen".into(), "observe".into(), "read_only".into()],
        },
        // ── Files (Level 0: Read-only, with restrictions) ──
        CapabilityDef {
            id: "pc.list_directory".into(),
            name: "List Directory".into(),
            description: "List files in a directory (sensitive dirs restricted).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 3000,
            tags: vec!["files".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.read_file".into(),
            name: "Read File".into(),
            description: "Read file content as text (max 10KB).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 3000,
            tags: vec!["files".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.search_files".into(),
            name: "Search Files".into(),
            description: "Search for files matching a pattern.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 5000,
            tags: vec!["files".into(), "observe".into()],
        },
        // ── System Info (Level 0) ─────────────────────────
        CapabilityDef {
            id: "pc.list_processes".into(),
            name: "List Processes".into(),
            description: "List all running processes with CPU/memory usage.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 2000,
            tags: vec!["process".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.network_info".into(),
            name: "Network Info".into(),
            description: "Get network information (hostname, IP, interfaces).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 1000,
            tags: vec!["network".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.disk_info".into(),
            name: "Disk Info".into(),
            description: "Get disk information (total/free space, mount points).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 1000,
            tags: vec!["disk".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.running_apps".into(),
            name: "Running Apps".into(),
            description: "List running applications with window titles.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 2000,
            tags: vec!["app".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.env_vars".into(),
            name: "Environment Variables".into(),
            description: "Get environment variables (secrets redacted).".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 500,
            tags: vec!["env".into(), "system".into(), "observe".into()],
        },
        CapabilityDef {
            id: "pc.cwd".into(),
            name: "Current Directory".into(),
            description: "Get current working directory.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 500,
            tags: vec!["dir".into(), "system".into(), "observe".into()],
        },
        // ── Window Management (Level 1: Safe action) ───────
        CapabilityDef {
            id: "pc.show_overlay".into(),
            name: "Show Overlay".into(),
            description: "Display a text overlay on screen (e.g., memo, notification).".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Displays UI overlay".into()],
            timeout_ms: 2000,
            tags: vec!["overlay".into(), "display".into()],
        },
        CapabilityDef {
            id: "pc.hide_overlay".into(),
            name: "Hide Overlay".into(),
            description: "Remove the current overlay from screen.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Removes UI overlay".into()],
            timeout_ms: 1000,
            tags: vec!["overlay".into(), "display".into()],
        },
        // ── Window Management (Level 1: Safe action) ───────
        CapabilityDef {
            id: "pc.launch_app".into(),
            name: "Launch Application".into(),
            description: "Launch an application by name or path.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Starts a process".into()],
            timeout_ms: 5000,
            tags: vec!["app".into(), "launch".into()],
        },
        CapabilityDef {
            id: "pc.focus_window".into(),
            name: "Focus Window".into(),
            description: "Bring a window to foreground by title or PID.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Changes window focus".into()],
            timeout_ms: 2000,
            tags: vec!["window".into(), "focus".into()],
        },
        CapabilityDef {
            id: "pc.resize_window".into(),
            name: "Resize Window".into(),
            description: "Resize a window to specified dimensions.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Resizes window".into()],
            timeout_ms: 2000,
            tags: vec!["window".into(), "resize".into()],
        },
        CapabilityDef {
            id: "pc.minimize_window".into(),
            name: "Minimize Window".into(),
            description: "Minimize a window.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Minimizes window".into()],
            timeout_ms: 1000,
            tags: vec!["window".into(), "minimize".into()],
        },
        CapabilityDef {
            id: "pc.maximize_window".into(),
            name: "Maximize Window".into(),
            description: "Maximize a window.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Maximizes window".into()],
            timeout_ms: 1000,
            tags: vec!["window".into(), "maximize".into()],
        },
        CapabilityDef {
            id: "pc.close_window".into(),
            name: "Close Window".into(),
            description: "Close a window (sends WM_CLOSE).".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Closes window".into()],
            timeout_ms: 2000,
            tags: vec!["window".into(), "close".into(), "approval_required".into()],
        },
        // ── Mouse (Level 1: Safe action) ───────────────────
        CapabilityDef {
            id: "pc.mouse_move".into(),
            name: "Mouse Move".into(),
            description: "Move mouse cursor to coordinates.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Moves mouse cursor".into()],
            timeout_ms: 1000,
            tags: vec!["mouse".into(), "input".into()],
        },
        CapabilityDef {
            id: "pc.mouse_drag".into(),
            name: "Mouse Drag".into(),
            description: "Drag mouse from one position to another.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Drags mouse".into()],
            timeout_ms: 3000,
            tags: vec!["mouse".into(), "input".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.mouse_scroll".into(),
            name: "Mouse Scroll".into(),
            description: "Scroll mouse wheel.".into(),
            safety_level: SafetyLevel::Level1SafeAct,
            requires_approval: false,
            side_effects: vec!["Scrolls".into()],
            timeout_ms: 1000,
            tags: vec!["mouse".into(), "input".into()],
        },
        // ── Input (Level 2: Approval required) ─────────────
        CapabilityDef {
            id: "pc.mouse_click".into(),
            name: "Mouse Click".into(),
            description: "Click at screen coordinates. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Clicks at coordinates".into()],
            timeout_ms: 3000,
            tags: vec!["mouse".into(), "input".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.keyboard_type".into(),
            name: "Keyboard Type".into(),
            description: "Type text via keyboard. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Inputs text".into()],
            timeout_ms: 5000,
            tags: vec![
                "keyboard".into(),
                "input".into(),
                "approval_required".into(),
            ],
        },
        CapabilityDef {
            id: "pc.press_hotkey".into(),
            name: "Press Hotkey".into(),
            description: "Press a keyboard shortcut. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Triggers keyboard shortcut".into()],
            timeout_ms: 2000,
            tags: vec![
                "keyboard".into(),
                "hotkey".into(),
                "approval_required".into(),
            ],
        },
        // ── File Operations (Level 2: Approval required) ──
        CapabilityDef {
            id: "pc.write_file".into(),
            name: "Write File".into(),
            description: "Write content to a file. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Writes to file".into()],
            timeout_ms: 5000,
            tags: vec!["files".into(), "write".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.delete_file".into(),
            name: "Delete File".into(),
            description: "Delete a file. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Deletes file".into()],
            timeout_ms: 3000,
            tags: vec!["files".into(), "delete".into(), "approval_required".into()],
        },
        // ── Process Management (Level 2: Approval required) ──
        CapabilityDef {
            id: "pc.kill_process".into(),
            name: "Kill Process".into(),
            description: "Kill a process by PID. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Kills process".into()],
            timeout_ms: 3000,
            tags: vec!["process".into(), "kill".into(), "approval_required".into()],
        },
        // ── Overlay Approval (Level 2) ─────────────────────
        CapabilityDef {
            id: "pc.discord_status".into(),
            name: "Discord RPC Status".into(),
            description: "Check Discord desktop IPC and local OAuth token readiness.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 3000,
            tags: vec!["discord".into(), "rpc".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.discord_get_guilds".into(),
            name: "Discord Guild List".into(),
            description: "List Discord guilds visible to the authenticated RPC session.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 5000,
            tags: vec!["discord".into(), "guild".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.discord_get_selected_voice_channel".into(),
            name: "Discord Selected Voice Channel".into(),
            description: "Read the currently selected Discord voice channel.".into(),
            safety_level: SafetyLevel::Level0Read,
            requires_approval: false,
            side_effects: vec![],
            timeout_ms: 3000,
            tags: vec!["discord".into(), "voice".into(), "read_only".into()],
        },
        CapabilityDef {
            id: "pc.discord_join_voice_by_name".into(),
            name: "Discord Join Voice By Name".into(),
            description: "Join a Discord voice channel by guild/server name and optional channel name. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Joins Discord voice channel".into()],
            timeout_ms: 10000,
            tags: vec!["discord".into(), "voice".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.discord_join_voice_channel".into(),
            name: "Discord Join Voice Channel".into(),
            description: "Join a Discord voice channel by channel id. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Joins Discord voice channel".into()],
            timeout_ms: 10000,
            tags: vec!["discord".into(), "voice".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.discord_leave_voice_channel".into(),
            name: "Discord Leave Voice Channel".into(),
            description: "Leave the currently selected Discord voice channel. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Leaves Discord voice channel".into()],
            timeout_ms: 5000,
            tags: vec!["discord".into(), "voice".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.discord_select_text_channel".into(),
            name: "Discord Select Text Channel".into(),
            description: "Select a Discord text channel in the desktop client. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Changes Discord selected text channel".into()],
            timeout_ms: 5000,
            tags: vec!["discord".into(), "text_channel".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.discord_set_voice_settings".into(),
            name: "Discord Set Voice Settings".into(),
            description: "Change Discord voice settings such as mute/deafen. REQUIRES APPROVAL.".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: true,
            side_effects: vec!["Changes Discord voice settings".into()],
            timeout_ms: 5000,
            tags: vec!["discord".into(), "voice_settings".into(), "approval_required".into()],
        },
        CapabilityDef {
            id: "pc.overlay_approval".into(),
            name: "Overlay Approval".into(),
            description: "Show overlay approval dialog (Y/N key).".into(),
            safety_level: SafetyLevel::Level2Approval,
            requires_approval: false,
            side_effects: vec!["Shows approval dialog".into()],
            timeout_ms: 30000,
            tags: vec!["overlay".into(), "approval".into()],
        },
    ]
}

/// Check if a capability requires approval.
pub fn requires_approval(cap_id: &str) -> bool {
    get_capabilities()
        .iter()
        .find(|c| c.id == cap_id)
        .map(|c| c.requires_approval)
        .unwrap_or(true) // Default to requiring approval if unknown
}
