#!/usr/bin/env python3
"""Generate AEGIS UI token artifacts and contrast report."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "design-tokens" / "tokens.json"
WEB_CSS = ROOT / "web-ui" / "src" / "styles" / "tokens.css"
ANDROID_COLORS = ROOT / "android-server" / "app" / "src" / "main" / "java" / "com" / "aegis" / "android" / "ui" / "designsystem" / "GeneratedTokens.kt"
CONTRAST_REPORT = ROOT / "design-tokens" / "contrast-report.json"


COLOR_NAMES = {
    "background": "bg",
    "surface": "surface",
    "surfaceElevated": "surface-elevated",
    "surfaceMuted": "surface-muted",
    "border": "border",
    "textPrimary": "text",
    "textSecondary": "text-secondary",
    "textMuted": "text-muted",
    "aegisCyan": "cyan",
    "cognitiveViolet": "violet",
    "success": "success",
    "warning": "warning",
    "critical": "critical",
    "offline": "offline",
    "white": "white",
}


ANDROID_NAMES = {
    "background": "AegisBackground",
    "surface": "AegisSurface",
    "surfaceElevated": "AegisSurfaceElevated",
    "surfaceMuted": "AegisSurfaceMuted",
    "border": "AegisBorder",
    "textPrimary": "AegisText",
    "textSecondary": "AegisTextSecondary",
    "textMuted": "AegisTextMuted",
    "aegisCyan": "AegisCyan",
    "cognitiveViolet": "AegisViolet",
    "success": "AegisSuccess",
    "warning": "AegisWarning",
    "critical": "AegisCritical",
    "offline": "AegisOffline",
    "white": "AegisWhite",
}


def main() -> None:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    colors = {key: value["value"] for key, value in tokens["color"].items()}
    WEB_CSS.write_text(render_css(tokens, colors), encoding="utf-8")
    ANDROID_COLORS.write_text(render_android(colors), encoding="utf-8")
    CONTRAST_REPORT.write_text(json.dumps(contrast_report(colors), indent=2), encoding="utf-8")


def render_css(tokens: dict, colors: dict[str, str]) -> str:
    lines = ["/* Generated by scripts/generate-design-tokens.py. Do not edit by hand. */", ":root {"]
    for key, value in colors.items():
        css_name = COLOR_NAMES[key]
        lines.append(f"  --aegis-{css_name}: {value.lower()};")
    for key, value in tokens["radius"].items():
        lines.append(f"  --radius-{key}: {value['value']};")
    for key, value in tokens["spacing"].items():
        lines.append(f"  --space-{key}: {value['value']};")
    for key, value in tokens["motion"].items():
        lines.append(f"  --motion-{key}: {value['value']};")
    lines.append(f"  --font-ui: {tokens['typography']['fontFamily']['value']};")
    lines.append(f"  --font-mono: {tokens['typography']['monoFamily']['value']};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_android(colors: dict[str, str]) -> str:
    lines = [
        "package com.aegis.android.ui.designsystem",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "// Generated by scripts/generate-design-tokens.py. Do not edit by hand.",
    ]
    for key, value in colors.items():
        color = value.upper().replace("#", "0xFF")
        lines.append(f"val {ANDROID_NAMES[key]} = Color({color})")
    lines.append("")
    return "\n".join(lines)


def contrast_report(colors: dict[str, str]) -> dict:
    pairs = [
        ("textPrimary", "background", "body-on-background"),
        ("textPrimary", "surface", "body-on-surface"),
        ("textSecondary", "background", "secondary-on-background"),
        ("textSecondary", "surface", "secondary-on-surface"),
        ("aegisCyan", "background", "accent-on-background"),
        ("warning", "background", "warning-on-background"),
        ("critical", "background", "critical-on-background"),
    ]
    results = []
    for fg, bg, label in pairs:
        ratio = contrast(colors[fg], colors[bg])
        results.append(
            {
                "id": label,
                "foreground": fg,
                "background": bg,
                "ratio": round(ratio, 2),
                "aa_body": ratio >= 4.5,
                "aa_large": ratio >= 3.0,
            }
        )
    return {"pairs": results, "all_aa_body": all(item["aa_body"] for item in results)}


def contrast(foreground: str, background: str) -> float:
    left = relative_luminance(foreground)
    right = relative_luminance(background)
    lighter, darker = max(left, right), min(left, right)
    return (lighter + 0.05) / (darker + 0.05)


def relative_luminance(hex_color: str) -> float:
    raw = hex_color.lstrip("#")
    channels = [int(raw[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    linear = [channel / 12.92 if channel <= 0.03928 else ((channel + 0.055) / 1.055) ** 2.4 for channel in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


if __name__ == "__main__":
    main()
