import {
  Activity,
  Bell,
  BrainCircuit,
  ClipboardList,
  Home,
  MessageSquare,
  MonitorCog,
  Settings as SettingsIcon,
  ShieldCheck
} from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { fetchOverview } from "./api/client";
import { useOverviewStream } from "./api/useOverviewStream";
import { ChatDrawer } from "./components/ChatDrawer";
import { Freshness } from "./components/Freshness";
import { StatusBadge } from "./components/StatusBadge";
import { ActivityPage } from "./pages/ActivityPage";
import { Approvals } from "./pages/Approvals";
import { CommandCenter } from "./pages/CommandCenter";
import { Display } from "./pages/Display";
import { MindMemory } from "./pages/MindMemory";
import { Settings } from "./pages/Settings";
import { Systems } from "./pages/Systems";
import { Work } from "./pages/Work";
import type { UiOverview } from "./types";

type PageId = "command" | "work" | "approvals" | "systems" | "mind" | "activity" | "settings";

const pages: Array<{ id: PageId; label: string; icon: typeof Home; path: string }> = [
  { id: "command", label: "Command Center", icon: Home, path: "/dashboard" },
  { id: "work", label: "Work", icon: ClipboardList, path: "/dashboard/work" },
  { id: "approvals", label: "Approvals", icon: ShieldCheck, path: "/dashboard/approvals" },
  { id: "systems", label: "Systems", icon: MonitorCog, path: "/dashboard/systems" },
  { id: "mind", label: "Mind & Memory", icon: BrainCircuit, path: "/dashboard/mind" },
  { id: "activity", label: "Activity", icon: Activity, path: "/dashboard/activity" },
  { id: "settings", label: "Settings", icon: SettingsIcon, path: "/settings" }
];

export function App() {
  const displayMode = window.location.pathname.startsWith("/display");
  const queryClient = useQueryClient();
  const [chatOpen, setChatOpen] = useState(window.location.pathname === "/chat");
  const selectedPage = useMemo(() => selectedPageFromPath(window.location.pathname), []);
  const [page, setPage] = useState<PageId>(selectedPage);
  const query = useQuery({
    queryKey: ["ui-overview", displayMode ? "display" : "dashboard"],
    queryFn: () => fetchOverview(displayMode ? "display" : "dashboard"),
    refetchInterval: displayMode ? 15_000 : 30_000
  });
  const onEvent = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: ["ui-overview"] });
  }, [queryClient]);
  useOverviewStream(onEvent, !displayMode);

  if (query.isLoading) return <LoadingDisplay displayMode={displayMode} />;
  if (query.isError || !query.data) return <ErrorDisplay message={query.error instanceof Error ? query.error.message : "Overview unavailable"} />;
  if (displayMode) return <Display overview={query.data} />;

  const overview = query.data;
  return (
    <div className="app-shell">
      <aside className="side-nav">
        <div className="brand">
          <span className="brand__name">AEGIS</span>
          <span className="brand__sub">Operational Console</span>
        </div>
        <nav className="nav-list" aria-label="Primary">
          {pages.map((item) => {
            const Icon = item.icon;
            return (
              <button
                className="nav-button"
                key={item.id}
                aria-current={page === item.id ? "page" : undefined}
                onClick={() => {
                  setPage(item.id);
                  window.history.pushState(null, "", item.path);
                }}
              >
                <Icon size={17} aria-hidden="true" />
                {item.label}
              </button>
            );
          })}
        </nav>
      </aside>
      <main className="content">
        <header className="top-bar">
          <div className="page-title">
            <h1>{pages.find((item) => item.id === page)?.label || "AEGIS"}</h1>
            <p>Live overview generated by Runtime managers, Policy, Approval, and Status services.</p>
          </div>
          <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
            <StatusBadge status={String(overview.core.data.health || "ONLINE")} />
            <Freshness generatedAt={overview.generated_at} sourceUpdatedAt={overview.freshness.source_updated_at} stale={overview.freshness.stale} />
            <button className="icon-button" onClick={() => setChatOpen(true)} title="Open chat">
              <MessageSquare size={17} aria-hidden="true" />
            </button>
          </div>
        </header>
        <Page page={page} overview={overview} />
      </main>
      <ChatDrawer open={chatOpen} onClose={() => setChatOpen(false)} />
    </div>
  );
}

function Page({ page, overview }: { page: PageId; overview: UiOverview }) {
  if (page === "work") return <Work overview={overview} />;
  if (page === "approvals") return <Approvals overview={overview} />;
  if (page === "systems") return <Systems overview={overview} />;
  if (page === "mind") return <MindMemory overview={overview} />;
  if (page === "activity") return <ActivityPage overview={overview} />;
  if (page === "settings") return <Settings />;
  return <CommandCenter overview={overview} />;
}

function selectedPageFromPath(path: string): PageId {
  if (path.includes("/work")) return "work";
  if (path.includes("/approvals")) return "approvals";
  if (path.includes("/systems") || path.includes("/servers")) return "systems";
  if (path.includes("/mind") || path.includes("/memory")) return "mind";
  if (path.includes("/activity") || path.includes("/audit")) return "activity";
  if (path.includes("/settings")) return "settings";
  return "command";
}

function LoadingDisplay({ displayMode }: { displayMode: boolean }) {
  return (
    <main className={displayMode ? "display-shell" : "app-shell"} style={{ display: "grid", placeItems: "center" }}>
      <section className="panel">
        <div className="panel__header"><h2>Loading AEGIS UI</h2><Bell size={18} /></div>
        <p className="muted">Waiting for the normalized overview service.</p>
      </section>
    </main>
  );
}

function ErrorDisplay({ message }: { message: string }) {
  return (
    <main className="display-shell" style={{ display: "grid", placeItems: "center" }}>
      <section className="panel">
        <div className="panel__header"><h2>AEGIS UI unavailable</h2><StatusBadge status="OFFLINE" /></div>
        <p className="muted">{message}</p>
      </section>
    </main>
  );
}
